baseURL: "https://medtechfest.netlify.app/"
theme: "up-business-theme"
languageCode: "en-us"

title: "MedTech"

# googleAnalytics: ""

summaryLength: 20

markup:
  goldmark:
    renderer:
      unsafe: true
      
params:
  title: "MedTech"
  description: "The AI & Health Science Festival is a transformative project aiming to promote dialogue around the use of AI in healthcare. It brings together students, professionals, and developers for an exchange of insights and ethical implications surrounding AI in the medical field."
  images:
    - "static/images/artificial-heart.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "Geschwister-Scholl-Platz 1, 80539 Munich, Germany"

  contact:
    - "human-ai [at] psy.lmu.de"

  copyright: "Unless otherwise noted, content on this site is licensed under a Creative Commons Attribution 4.0 International license. This means that you are free to copy, distribute, and adapt our work, as long as you attribute the work to 'AI & Health Science Festival' and abide by other license terms."

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "MedTechFest"
      url: "/#medtechfest"
      weight: 2

    - name: "MedTechTalk"
      url: "/#medtechtalk"
      weight: 3

    - name: "Our Team"
      url: "/#team"
      weight: 4

    - name: "Science Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Contact us"
      url: "/contact"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "MedTechFest"
      url: "/#medtechfest"
      weight: 2

    - name: "MedTechTalk"
      url: "/#medtechtalk"
      weight: 3

    - name: "Our Team"
      url: "/#team"
      weight: 4

    - name: "Science Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
